language: ruby
cache: bundler
env:
  DATABASE_URL: postgres://postgres@localhost:5432/travis_ci_test
node_js:
  - "0.10"
rvm:
  - 2.1.5
before_script:
  - npm install -g bower
  - bower install
  - psql -c 'create database travis_ci_test;' -U postgres
  - ./bin/sequel -m db/migrations/ postgres://postgres@localhost:5432/travis_ci_test
