sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
    - tmp/cache/assets/test
    - vendor/assets/bower_components
env:
  global:
    - secure: "Q+A79g0m3SyD3QMNi4vIWl9vMclClXQqojUnZb/8a2gMKlFCj82+odpqY0XRHqWanAy4VTzf3JoiSFam7shgaYbVAczFHjeym9ddgEE6mq4O6wh4a2JjME8lCkSjgpvW0aL7pKtH4PVUNppIFL/EuErFw38ltL30ur4u3Kj0qGA="
    - secure: "BJwdnDXgtrta3KZ2XSJYQM5fThbyrcpODMzDIIUne5NBTG7SBMpbvS0op3Fa+Xip9GaL6CsoFOMn9u0D1rzGFKafLaa70qOt96Q6JcloAor4Ksm5sntwtWu1VGSJ9fXrxqsObX+pTBq3HPHfhOIgyIlkN8OfUpbrK8zQqoxJNQU="
    - DATABASE_URL=postgres://postgres@localhost:5432/travis_ci_test
node_js:
  - "0.10"
rvm:
  - 2.1.5
before_script:
  - npm install
  - psql -c 'create database travis_ci_test;' -U postgres
  - ./bin/sequel -m db/migrations/ postgres://postgres@localhost:5432/travis_ci_test
after_script:
  - ./node_modules/.bin/travis-notify-geckoboard -a $GECKOBOARD_API_KEY -w $GECKOBOARD_WIDGET_KEY
deploy:
  provider: heroku
  app: ggp-register-interest
  api_key:
    secure: MkoZagFaPslKSNelShv4rN827K6jd3Gp2PdCC/6lKJavA8LTnNzBv60yugZy1cUhjHGFMem2ZSOf1dRjRJrzgCCx9arMoHZMgK9dm/m4XEQN7qQd2ry3zEKbR9MrBLhMAzF6Yj3pqnqVEVcj9L0K83zoqn2oEwsI+Wo6Oh0yuis=
  on:
    repo: guidance-guarantee-programme/register_your_interest
