language: ruby
cache: bundler
env:
  DATABASE_URL: postgres://postgres@localhost:5432/travis_ci_test
node_js:
  - "0.10"
rvm:
  - 2.1.5
before_script:
  - npm install
  - psql -c 'create database travis_ci_test;' -U postgres
  - ./bin/sequel -m db/migrations/ postgres://postgres@localhost:5432/travis_ci_test
after_script:
  - ./node_modules/.bin/travis-notify-geckoboard -a CtWcva5bwhpLmPgta2ep0lro6vqQ80guqhupcxl+v7pgmhKq7PwbLm8E8XESGlaZWIO4qCcjRj9TUsHCFRLk1SnZE5ZKXeVWOq8lh066saFKckjpKARsb2V1Mxa6du9eJms9lAynEHHnYt0Y6spHmxIni5q2HjWoBDtmiSydaGU= -w c4+l9mP4qFbu1ORNMgrfhU6Kvq03PPlSQmsfSGWVszXq4mAPhKqucGaHme5X01xj/V9w/9VGPYY+ad0EYUNDIveTaoD08gOiczay9fJupWwFQm1aZ7tHyNuRKV6/L6QGZO+LXWClFuTanigSf2Y8Rs0WNAbIiHibNtLAdghAtlQ=
deploy:
  provider: heroku
  app: ggp-register-interest
  api_key:
    secure: MkoZagFaPslKSNelShv4rN827K6jd3Gp2PdCC/6lKJavA8LTnNzBv60yugZy1cUhjHGFMem2ZSOf1dRjRJrzgCCx9arMoHZMgK9dm/m4XEQN7qQd2ry3zEKbR9MrBLhMAzF6Yj3pqnqVEVcj9L0K83zoqn2oEwsI+Wo6Oh0yuis=
  on:
    repo: guidance-guarantee-programme/register_your_interest
